[[main]]
  identifier = "updates"
  name = "Updates"
  url = "updates"
  weight = 1

[[main]]
  identifier = "docs"
  name = "Study"
  url = "docs"
  weight = 2

[[main]]
  identifier = "web"
  name = "Web"
  url = "web"
  weight = 3

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 4